include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    non_constant_identifier_names: ignore
    constant_identifier_names: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
